title: Colette Snow
email: colette@colettesnow.com
description: >- # this means to ignore newlines until "baseurl:"
  Writer/Blogger at Mana with Tea, Gamer, Anime/Manga and Drama fan, and co-founder of Muse's Success.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://colettesnow.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: colette_snow
github_username:  colettesnow

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-paginate

# Pages
paginate: 10
paginate_path: "/stream/page:num/"

include:
  - _headers
  - robots.txt
  - ads.txt
  
collections:
  portfolio:
    output: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
